// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REQUEST = "REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

// MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// LOADER
export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";

// GROUP INFO
export const SET_GROUP = "SET_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const SWITCH_GROUP = "SWITCH_GROUP";
export const CLEAR_GROUP = "CLEAR_GROUP";
export const SET_FETCH = "SET_FETCH";
export const SET_DASHBOARD = "SET_DASHBOARD";

// USER INFO
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const IS_ADMIN = "IS_ADMIN";
export const CLEAR_USER = "CLEAR_USER";

// USER CONTRIBUTIONS
export const SET_USER_CONTRIBUTION = "SET_USER_CONTRIBUTION";
export const CLEAR_USER_CONTRIBUTION = "CLEAR_USER_CONTRIBUTION";

// PAYMENT
export const ACCEPT_PAYMENT = "ACCEPT_PAYMENT";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const PENDING_PAYMENTS = "PENDING_PAYMENTS";

// USER PAYMENTS
export const SET_USER_PAYMENTS = "SET_USER_PAYMENTS";
export const SET_USER_PENDING_LIST = "SET_USER_PENDING_LIST";
export const CLEAR_USER_PENDING_LIST = "CLEAR_USER_PENDING_LIST";

// GROUP PAYMENT HISTORY
export const SET_GROUP_PAYMENT_HISTORY = "SET_GROUP_PAYMENT_HISTORY";
export const CLEAR_GROUP_PAYMENT_HISTORY = "CLEAR_GROUP_PAYMENT_HISTORY";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const SET_REPORT_PAYMENT = "SET_REPORT_PAYMENT";

// MEMBERS
export const SET_MEMBERS = "SET_MEMBERS";
export const SET_NON_MEMBERS = "SET_NON_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";

// TRANSACTIONS
export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_DONATION = "ADD_DONATION";

// HISTORY TRANSACTIONS
export const SET_TRANSACTION = "SET_TRANSACTION";
export const HISTORY_FILTER_CHANGE = "HISTORY_FILTER_CHANGE";
export const SET_REPORT_TRANSACTION = "SET_REPORT_TRANSACTION";
export const CLEAR_TRANSACTION = "CLEAR_TRANSACTION";
